### ISSUE TITLE
電車の遅延があったら教えてくれる

### ISSUE THREAD

**Issue by momiji53** [Supper-of-Developers/remindanuki#12]
## 課題
任意のタイミング（朝とか）に電車の遅延を教えてくれる機能が欲しい。
出来ればユーザーごとに管理したい。

## 理由
電車遅れてたら教えてくれたら便利。

**Comment by atsushi-niwayama** [comment]
出来ればユーザーごとに管理したい。の部分は電線わかったらその情報教えるということでいいですか？

**Comment by atsushi-niwayama** [comment]
１遅延情報って知らせたらレスポンスがくる

出来たら↓
最初の目標は都内の路線の遅延の電車がありましたら、情報を提供するということですね。
朝８時から９時ごろでお間違い無いですか？
電車登録とユーザーが記載したら登録して、ユーザーに路線の入力を促し、遅延情報を知らせると。（できたら）（複数の電車の情報を取得する必要あり、XX線とか言い方の違いを汲み取る）

＊登録方法などを教えてくれるリッチメニューの追加を別issueで検討

例：XX線がXX分遅れてるぽん。
　：現在正常に動いてるぽん。

**Comment by momiji53** [comment]
問題ありません。
まずは1番の実装をお願いします。

**Comment by atsushi-niwayama** [comment]
追記です。今回知らせる曜日は月曜日から金曜日で設定させていただきますがよろしいでしょうか？

**Comment by momiji53** [comment]
通勤時にお知らせしてもらいたいだけなので、それで問題ありません。

**Comment by atsushi-niwayama** [comment]
東銀座、新橋、銀座の乗り入れ線の情報を提供するように設計させていただきますがよろしいでしょうか

**Comment by atsushi-niwayama** [comment]
https://github.com/Supper-of-Developers/remindanuki/issues/45　に関連機能のブランチ立てました
