### ISSUE TITLE
天気を言う機能

### ISSUE THREAD

**Issue by RyosukeMaruyama** [Supper-of-Developers/remindanuki#13]
天気を教えて等言うと教えてくれる機能

**Comment by atsushi-niwayama** [comment]
天気を教えて、天気、weather、気温、何度、って聞かれたら天気を教える機能を実装しようと教えようと思いますが、
表示される内容は、最高気温、最低気温、現在の気温を記載すればいいですか？

**Comment by RyosukeMaruyama** [comment]
天気が知りたいのですが

**Comment by RyosukeMaruyama** [comment]
最高気温、最低気温も良いですがまずシンプルに天気が知りたいです

**Comment by atsushi-niwayama** [comment]
要望まずシンプルに天気を知りたい。
トリガーする用語　天気は？天気、天気？気温、気温？（天気および気温が部分一致したときトリガーする）
天気は東京の気象情報をしりたい。
雨が降る場合は特に知らせてほしい（別のissueで対応します。）

内容：東京の天気はxxだぽん。
 　　　最高気温はxx度だぽん。
　　　最低気温はxx度だぽん。

上記の内容で作成しますがよろしいでしょうか？

**Comment by RyosukeMaruyama** [comment]
よろしくお願いします。
