### ISSUE TITLE
反応する言葉を増やしたい

### ISSUE THREAD

**Issue by momiji53** [Supper-of-Developers/remindanuki#24]
例：
新しいリマインダ→「新規作成」など
キャンセル→「やっぱりやめる」「もういい」「削除」など

**Comment by atsushi-niwayama** [comment]
反応する言葉の追加は、新規のリマインダと予定のキャンセルのみでいいですか？
新規は3種類（もし見つかればその都度質問し追加）、キャンセルは「やっぱりやめる」「もういい」「削除」「いらない」を予定しておりますがよろしいでしょうか？

**Comment by momiji53** [comment]
新規とキャンセルに追加してください。
キャンセル時には「やめる」「もういい」「削除」「いらない」を追加してください。

日付設定時にキャンセルするためには「キャンセル」と入力してくださいというメッセージが表示されるのですが、そちらにもメッセージを追加するようにお願いします。

**Comment by atsushi-niwayama** [comment]
今回反応する言葉は

新しいリマインダ→「新規作成」「追加」、「ついか」、「予定」「よてい」
昨日3種類と記載しましたが、日々使うと面倒臭くなって平仮名で入力すると思いまして、平仮名も入れようと思うのですが、いかがでしょうか？

キャンセル時には「やめる」「もういい」「削除」「いらない」
こちらは要望通り実装しようと思いますがいかがでしょうか。

**Comment by momiji53** [comment]
ひらがなを入れるのでも実装しておいてください。
ただ、あまり入れすぎるとコードも汚くなってしまうので、工夫してください。

https://www.pythonweb.jp/tutorial/list/index10.html
コンフィグに反応する言葉のリストを定義しておいて、こういうのでマッチングとかもありです。
