### ISSUE TITLE
リッチメニューの実装

### ISSUE THREAD

**Issue by momiji53** [Supper-of-Developers/remindanuki#27]
現状、LINE Developersのウェブ画面からリッチメニューを設定しているが、APIのほうでJSONを送ることでリッチメニューを表示できる機能があるので、そちらに移行したい。

**Comment by park-jungeun** [comment]
リッチメニューの実装について
- ４等分に分け、以下のように各部分を押すと該当テキストが入力されるようにする予定です。

　リマインド追加　   | 　一覧を見る　
---------------------+------------------
           会話する　　   |     リマインダヌキの紹介

- 友達登録の時、リッチメニューが反映されるようにする予定です。

以上でよろしいでしょうか？

**Comment by momiji53** [comment]
問題ありません。
紹介などにどんなことを書くかなどは他の方と話し合いながら決めて、もう一度報告くれると嬉しいです。
