### ISSUE TITLE
ちょっとした会話がしたい

### ISSUE THREAD

**Issue by momiji53** [Supper-of-Developers/remindanuki#7]
## 課題
「ありがとう」って言ったら「どういたしまして」とか返して欲しい。

## 理由
予定を教えてくれるのはいいが、なんか味気ない。
単純なものでいいのでいくつか言葉に反応する裏機能が欲しい。

**Comment by momiji53** [comment]
オウム返しじゃちょっと味気ないので、おはようと言ったら「おはよう！今日も一日頑張ろう！」とかの方が良いです！
他もタヌキっぽく語尾を工夫してくれると嬉しいです。

**Comment by park-jungeun** [comment]
タヌキっぽい語尾として、「ポン」が代表的に使われていると思います。それを適応してみました。
以下の内容でよろしいでしょうか？

例）「おはよう」ー「おはよう！今日も１日頑張るぞいポン！」
　　「ありがとう」ー「どういたしましてポン！」
　　「さよなら」ー「さよなら！いつでも呼んでねポン〜」

その他、会話する時は、語尾だけでなくタヌキの出身を関西と仮定して関西弁を使う事も考えて見ました。これはどうですか？

例）「おはよう」ー　「おはようポン！今日１日もキバるで！」
　　「ありがとう」ー「ええでええで〜」
　　「さよなら」ー　「おおきに！いつでも呼んだってなポン！」
