### ISSUE TITLE
セリフの語尾とかがランダムに変わるようにしたい

### ISSUE THREAD

**Issue by momiji53** [Supper-of-Developers/remindanuki#8]
## 課題
返ってくるセリフにランダム性を持たせたい。

## 理由
喋るセリフが1パターンで面白みがない。
リマインくんは予定をリマインドするときに「頑張って！」とか「落ち着いて！」とか言ってくれる。

**Comment by park-jungeun** [comment]
予定をリマインドするときに「〜の時間だぽん！」セリフの後ろに、 
「ファイトだぽん！」、「急いでたぬ！」「覚えてたかな…」
以上の３種類のセリフがランダムに出るように考えていますが、よろしいでしょうか？

**Comment by momiji53** [comment]
問題ないです。
その3種類でお願いします。
